#!/bin/sh -efu
### This file is covered by the GNU General Public License,
### which should be included with libshell as the file LICENSE.
### All copyright information are listed in the COPYING.

if [ -z "${__included_shell_version-}" ]; then
__included_shell_version=1

libshell_vmajor=0
libshell_vminor=3
libshell_vpatch=0

libshell_version=3

__export_compatibility_string_quote_remove=1

fi #__included_shell_version
