#!/bin/ash -efu

normalize() {
	sed \
		-e "s/\"/'/g" \
		-e 's/[[:space:]]\+/ /g' \
		-e 's/^[[:space:]]\+//' \
		-e 's/[[:space:]]\+$//'
}

getopt_test001() { # UnitTest
	LANG=C
	expect=`{ getopt -n TEST -o ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

getopt_test002() { # UnitTest
	LANG=C
	expect=`{ getopt -n TEST -o ' ' ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o ' ' ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

getopt_test003() { # UnitTest
	LANG=C
	expect=`{ getopt -n TEST -o '' -l ' ' -- ZZZ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o '' -l ' ' -- ZZZ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}


getopt_test004() { # UnitTest
	LANG=C
	expect=`{ getopt -n TEST -o 'a,b,c' -- -abc -a -b -c ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o 'a,b,c' -- -abc -a -b -c ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

getopt_test005() { # UnitTest
	LANG=C
	expect=`{ getopt -n TEST -o 'a,b,c' -l 'caa:,cba:' -- -abc --caa 'AAA' --cba='BBB' ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o 'a,b,c' -l 'caa:,cba:' -- -abc --caa 'AAA' --cba='BBB' ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

getopt_test006() { # UnitTest
	LANG=C
	expect=`{ getopt -n TEST -o 'a,b,c' -l 'caa:,cba:' -- --cb 'AAA' --c='BBB' ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o 'a,b,c' -l 'caa:,cba:' -- --cb 'AAA' --c='BBB' ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

getopt_test007() { # UnitTest
	LANG=C
	expect=`{ getopt -n TEST -o 'a,b,c' -l 'caa:,cba:' -- --cbz 'AAA' --c='BBB' ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o 'a,b,c' -l 'caa:,cba:' -- --cbz 'AAA' --c='BBB' ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

getopt_test008() { # UnitTest
	LANG=C
	expect=`{ getopt -a -n TEST -o 'a,b,c' -l 'caa:,cba:' -- -cb 'AAA' ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -a -n TEST -o 'a,b,c' -l 'caa:,cba:' -- -cb 'AAA' ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

getopt_test009() { # UnitTest
	LANG=C
	expect=`{ getopt -a -n TEST -o 'a,b,c' -l 'caa:,cba:' -- -c='AAA' ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -a -n TEST -o 'a,b,c' -l 'caa:,cba:' -- -c='AAA' ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

getopt_test010() { # UnitTest
	LANG=C
	expect=`{ getopt -n TEST -o 'a,b,c' -l 'caa:,cba:' -- -c='AAA'; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o 'a,b,c' -l 'caa:,cba:' -- -c='AAA'; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	(assertEquals "$result" "$result" "$expect") ||:
	shouldSkip
}

getopt_test011() { # UnitTest
	LANG=C
	expect=`{ getopt -n TEST -o 'a,b,c' -l 'abcd:,cbce:' -- --abcx 'AAA'; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o 'a,b,c' -l 'abcd:,cbce:' -- --abcx 'AAA'; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

getopt_test012() { # UnitTest
	LANG=C
	expect=`{ getopt -n TEST -o 'a:,b,c' -- -abc 'AAA'; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o 'a:,b,c' -- -abc 'AAA'; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

getopt_test013() { # UnitTest
	LANG=C
	expect=`{ getopt -n TEST -o 'a::,b,c' -- -a -bc 'AAA'; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o 'a::,b,c' -- -a -bc 'AAA'; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

getopt_test014() { # UnitTest
	LANG=C
	expect=`{ getopt -n TEST -o 'a,b,c' -l 'caa:,cba:' -- 'BBB' 'XXX ZZZ'; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o 'a,b,c' -l 'caa:,cba:' -- 'BBB' 'XXX ZZZ'; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

getopt_test015() { # UnitTest
	LANG=C
	expect=`{ getopt -n TEST -o '+a,b,c' -l 'caa:,cba:' -- --caa='AAA' 'BBB' --zzz -x; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o '+a,b,c' -l 'caa:,cba:' -- --caa='AAA' 'BBB' --zzz -x; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}


getopt_test016() { # UnitTest
	LANG=C
	expect=`{ getopt -n TEST -o '-a,b,c' -l 'caa:,cba:' -- 'AAA' --caa='BBB' 'CCC'; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o '-a,b,c' -l 'caa:,cba:' -- 'AAA' --caa='BBB' 'CCC'; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

getopt_test017() { # UnitTest
	LANG=C
	. ../shell-getopt
	expect=' -a -b -- 
 -a -b -- 
 -a -b -- '
	result=`for i in 1 2 3; do getopt -n TEST -o 'a,b' -- -ab; done 2>&1`
	assertEquals "$result" "$result" "$expect"
}

getopt_test018() { # UnitTest
	LANG=C
	expect=`{ getopt -n TEST -o '' -l 'tag:,tag-message:' -- ZZZ --tag=xxx; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o '' -l 'tag:,tag-message:' -- ZZZ --tag=xxx; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

getopt_test019() { # UnitTest
	LANG=C
	expect=`{ getopt -n TEST -o '' -l 'tag-message:,tag:' -- ZZZ --tag=xxx; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o '' -l 'tag-message:,tag:' -- ZZZ --tag=xxx; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

getopt_test020() { # UnitTest
	LANG=C
	expect=`{ getopt -n TEST -o '' -l 'tag-message:,tag:,tag-subject:' -- ZZZ --tag=xxx; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o '' -l 'tag-message:,tag:,tag-subject:' -- ZZZ --tag=xxx; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}
