#!/bin/ash -efu

ini_config_comment_test1() { # UnitTest
	. ../shell-ini-config

	cp -f -- ini-config/z.ini ini-config/ini_config_comment-t1.ini

	ini_config_comment ini-config/ini_config_comment-t1.ini sect1

	local rc=0
	cmp -s ini-config/ini_config_comment-t1.ini ini-config/ini_config_comment-t1.ini.expect || rc=$?

	[ "$rc" != 0 ] ||
		rm -f  -- ini-config/ini_config_comment-t1.ini

	assertTrue $rc
}

ini_config_comment_test2() { # UnitTest
	. ../shell-ini-config

	cp -f -- ini-config/test2.ini ini-config/ini_config_comment-t2.ini

	ini_config_comment ini-config/ini_config_comment-t2.ini mysection

	local rc=0
	cmp -s ini-config/ini_config_comment-t2.ini ini-config/ini_config_comment-t2.ini.expect || rc=$?

	[ "$rc" != 0 ] ||
		rm -f  -- ini-config/ini_config_comment-t2.ini

	assertTrue $rc
}

ini_config_comment_test3() { # UnitTest
	. ../shell-ini-config

	cp -f -- ini-config/test3.ini ini-config/ini_config_comment-t3.ini

	ini_config_comment ini-config/ini_config_comment-t3.ini mysection

	local rc=0
	cmp -s ini-config/ini_config_comment-t3.ini ini-config/ini_config_comment-t3.ini.expect || rc=$?

	[ "$rc" != 0 ] ||
		rm -f  -- ini-config/ini_config_comment-t3.ini

	assertTrue $rc
}

ini_config_comment_test4() { # UnitTest
        . ../shell-ini-config
        cp -f ini-config/krb5.include.conf ini-config/ini_config_comment-t4.ini

        ini_config_comment ini-config/ini_config_comment-t4.ini realms

        local rc=0
        cmp -s ini-config/ini_config_comment-t4.ini ini-config/ini_config_comment-t4.ini.expect || rc=$?

        [ "$rc" != 0 ] ||
                rm -f  -- ini-config/ini_config_comment-t4.ini

        assertTrue $rc
}
