#!/bin/sh -efu

srcdir="$(readlink -ev ..)"
export PATH="$srcdir:$PATH"

. ../shell-unittest

WORKDIR=
setUpTests() {
	WORKDIR="$(mktemp -d "$PROG.XXXXXXXXX")"
}

tearDownTests() {
	rm -rf -- "$WORKDIR"
}

for s in \
	quote_sed_regexp quote_shell string_quote_remove \
	opt_check_dir opt_check_number opt_check_read \
	quote_sed_regexp_variable quote_shell_variable \
	getopt signal \
	fatal message verbose \
	quote_shell_args \
	ini_config_get ini_config_set \
	git_config_get git_config_count git_config_list git_config_set git_config_unset \
	shell_var_unquote shell_var_trim \
	fill_mask \
	cmdline_get \
	run_scripts \
	;
do
	[ -z "${TEST-}" -o "${TEST-}" = "$s" ] ||
		continue
	. "./$s"
	registerTests "./$s"
done

runUnitTests
