#!/bin/sh

shell_var_unquote_test1() { # UnitTest
	. ../shell-var

	local result string='"test passed"'
	shell_var_unquote result "$string"
	assertEquals "$string" "$result" 'test passed'
}

shell_var_unquote_test2() { # UnitTest
	. ../shell-var

	local result string="'test passed'"
	shell_var_unquote result "$string"
	assertEquals "$string" "$result" 'test passed'
}

shell_var_unquote_test3() { # UnitTest
	. ../shell-var

	local result string="'test passed\""
	shell_var_unquote result "$string"
	assertEquals "$string" "$result" "'test passed\""
}

shell_var_unquote_test4() { # UnitTest
	. ../shell-var

	local result string="test ' passed"
	shell_var_unquote result "$string"
	assertEquals "$string" "$result" "test ' passed"
}
