#!/bin/sh

string_quote_remove_test1() { # UnitTest
	. ../shell-quote

	local string='"test passed"'
	local result="$(string_quote_remove "$string")"
	assertEquals "$string" "$result" 'test passed'
}

string_quote_remove_test2() { # UnitTest
	. ../shell-quote

	local string="'test passed'"
	local result="$(string_quote_remove "$string")"
	assertEquals "$string" "$result" 'test passed'
}

string_quote_remove_test3() { # UnitTest
	. ../shell-quote

	local string="'test passed\""
	local result="$(string_quote_remove "$string")"
	assertEquals "$string" "$result" "'test passed\""
}

string_quote_remove_test4() { # UnitTest
	. ../shell-quote

	local string="test ' passed"
	local result="$(string_quote_remove "$string")"
	assertEquals "$string" "$result" "test ' passed"
}
