#!/bin/ash -efu

normalize() {
	sed \
		-e "s/\"/'/g" \
		-e 's/[[:space:]]\+/ /g' \
		-e 's/^[[:space:]]\+//' \
		-e 's/[[:space:]]\+$//'
}

appendTests getopt_test1
getopt_test1() {
	LANG=C
	expect=`{ getopt -n TEST -o ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

appendTests getopt_test2
getopt_test2() {
	LANG=C
	expect=`{ getopt -n TEST -o ' ' ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o ' ' ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

appendTests getopt_test3
getopt_test3() {
	LANG=C
	expect=`{ getopt -n TEST -o '' -l ' ' -- ZZZ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o '' -l ' ' -- ZZZ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}


appendTests getopt_test4
getopt_test4() {
	LANG=C
	expect=`{ getopt -n TEST -o 'a,b,c' -- -abc -a -b -c ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o 'a,b,c' -- -abc -a -b -c ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

appendTests getopt_test5
getopt_test5() {
	LANG=C
	expect=`{ getopt -n TEST -o 'a,b,c' -l 'caa:,cba:' -- -abc --caa 'AAA' --cba='BBB' ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o 'a,b,c' -l 'caa:,cba:' -- -abc --caa 'AAA' --cba='BBB' ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

appendTests getopt_test6
getopt_test6() {
	LANG=C
	expect=`{ getopt -n TEST -o 'a,b,c' -l 'caa:,cba:' -- --cb 'AAA' --c='BBB' ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o 'a,b,c' -l 'caa:,cba:' -- --cb 'AAA' --c='BBB' ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

appendTests getopt_test7
getopt_test7() {
	LANG=C
	expect=`{ getopt -n TEST -o 'a,b,c' -l 'caa:,cba:' -- --cbz 'AAA' --c='BBB' ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o 'a,b,c' -l 'caa:,cba:' -- --cbz 'AAA' --c='BBB' ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

appendTests getopt_test8
getopt_test8() {
	LANG=C
	expect=`{ getopt -a -n TEST -o 'a,b,c' -l 'caa:,cba:' -- -cb 'AAA' ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -a -n TEST -o 'a,b,c' -l 'caa:,cba:' -- -cb 'AAA' ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

appendTests getopt_test9
getopt_test9() {
	LANG=C
	expect=`{ getopt -a -n TEST -o 'a,b,c' -l 'caa:,cba:' -- -c='AAA' ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -a -n TEST -o 'a,b,c' -l 'caa:,cba:' -- -c='AAA' ; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

appendTests getopt_test10
getopt_test10() {
	LANG=C
	expect=`{ getopt -n TEST -o 'a,b,c' -l 'caa:,cba:' -- -c='AAA'; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o 'a,b,c' -l 'caa:,cba:' -- -c='AAA'; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

appendTests getopt_test11
getopt_test11() {
	LANG=C
	expect=`{ getopt -n TEST -o 'a,b,c' -l 'abcd:,cbce:' -- --abcx 'AAA'; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o 'a,b,c' -l 'abcd:,cbce:' -- --abcx 'AAA'; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

appendTests getopt_test12
getopt_test12() {
	LANG=C
	expect=`{ getopt -n TEST -o 'a:,b,c' -- -abc 'AAA'; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o 'a:,b,c' -- -abc 'AAA'; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

appendTests getopt_test13
getopt_test13() {
	LANG=C
	expect=`{ getopt -n TEST -o 'a::,b,c' -- -a -bc 'AAA'; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o 'a::,b,c' -- -a -bc 'AAA'; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

appendTests getopt_test14
getopt_test14() {
	LANG=C
	expect=`{ getopt -n TEST -o 'a,b,c' -l 'caa:,cba:' -- 'BBB' 'XXX ZZZ'; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o 'a,b,c' -l 'caa:,cba:' -- 'BBB' 'XXX ZZZ'; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

appendTests getopt_test15
getopt_test15() {
	LANG=C
	expect=`{ getopt -n TEST -o '+a,b,c' -l 'caa:,cba:' -- --caa='AAA' 'BBB' --zzz -x; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o '+a,b,c' -l 'caa:,cba:' -- --caa='AAA' 'BBB' --zzz -x; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}


appendTests getopt_test16
getopt_test16() {
	LANG=C
	expect=`{ getopt -n TEST -o '-a,b,c' -l 'caa:,cba:' -- 'AAA' --caa='BBB' 'CCC'; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	. ../shell-getopt
	result=`{ getopt -n TEST -o '-a,b,c' -l 'caa:,cba:' -- 'AAA' --caa='BBB' 'CCC'; echo rc=$?; } 2>&1 |normalize |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}
