#!/bin/ash -efu

PROG='TEST'

appendTests message_test1
message_test1() {
	. ../shell-error
	expect="$PROG: message message;"
	result=`message "message message" 2>&1 |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

appendTests message_test2
message_test2() {
	. ../shell-error
	expect="$PROG: message;message;"
	result=`message "message
message" 2>&1 |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

appendTests message_test3
message_test3() {
	. ../shell-error
	zzz=ZZZ
	expect="$PROG: message ZZZ message;"
	result=`message "message $zzz message" 2>&1 |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

appendTests message_test4
message_test4() {
	. ../shell-error
	expect="$PROG: message message;another message;"
	result=`{ message "message message" 2>&1; echo "another message"; } |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}
