#!/bin/ash -efu

appendTests opt_check_number_test1
opt_check_number_test1() {
	. ../shell-args

	string="1234"
	expect="1234"
	result="$(opt_check_number "NUM" "$string" 2>&1)" ||:

	if [ "$result" != "$expect" ]; then
		printf '%s' "$result"
		return 1
	fi
}

appendTests opt_check_number_test2
opt_check_number_test2() {
	. ../shell-args

	string="0001"
	expect="$(message "NUM: $string: invalid number." 2>&1)"
	result="$(opt_check_number "NUM" "$string" 2>&1)" ||:

	if [ "$result" != "$expect" ]; then
		printf '%s' "$result"
		return 1
	fi
}

appendTests opt_check_number_test3
opt_check_number_test3() {
	. ../shell-args

	string="1 2"
	expect="$(message "NUM: $string: invalid number." 2>&1)"
	result="$(opt_check_number "NUM" "$string" 2>&1)" ||:

	if [ "$result" != "$expect" ]; then
		printf '%s' "$result"
		return 1
	fi
}
