#!/bin/ash -efu

appendTests quote_shell_test1
quote_shell_test1() {
	. ../shell-quote
	local string='`true`'
	local result
	eval "result=\"$(quote_shell "$string")\""
	if [ "$result" != "$string" ]; then
		printf '%s' "$string"
		return 1
	fi
}

appendTests quote_shell_test2
quote_shell_test2() {
	. ../shell-quote
	local string='$(true)'
	local result
	eval "result=\"$(quote_shell "$string")\""
	if [ "$result" != "$string" ]; then
		printf '%s' "$string"
		return 1
	fi
}

appendTests quote_shell_test3
quote_shell_test3() {
	. ../shell-quote
	local string='\`true\`; echo zzz'
	local result
	eval "result=\"$(quote_shell "$string")\""
	if [ "$result" != "$string" ]; then
		printf '%s' "$string"
		return 1
	fi
}
