#!/bin/ash -efu

appendTests quote_sed_regexp_test1
quote_sed_regexp_test1() {
	. ../shell-quote
	local string='.*'
	local regexp="$(quote_sed_regexp "$string")"
	local result="$(printf '%s\n' "$string passed" |sed -e "s/^$regexp/test/")"
	assertEquals "$string" "$result" 'test passed'
}

appendTests quote_sed_regexp_test2
quote_sed_regexp_test2() {
	. ../shell-quote
	local string='[[:space:]]'
	local regexp="$(quote_sed_regexp "$string")"
	local result="$(printf '%s\n' "test $string" |sed -e "s/$regexp/passed/")"
	assertEquals "$string" "$result" 'test passed'
}

appendTests quote_sed_regexp_test3
quote_sed_regexp_test3() {
	. ../shell-quote
	local string='t{1,3}'
	local regexp="$(quote_sed_regexp "$string")"
	local result="$(printf '%s\n' "test$string passed" |sed -e "s/$regexp//")"
	assertEquals "$string" "$result" 'test passed'
}

appendTests quote_sed_regexp_test4
quote_sed_regexp_test4() {
	. ../shell-quote
	local string='&\1'
	local regexp="$(quote_sed_regexp "$string")"
	local result="$(printf '%s\n' "test not passed" |sed -e "s/\(not\)/$regexp/")" #"
	assertEquals "$string" "$result" 'test &\1 passed'
}
