#!/bin/ash -efu

srcdir="$(readlink -ev ..)"
export PATH="$srcdir:$PATH"

. ../shell-unittest

WORKDIR=
setUpTests() {
	WORKDIR="$(mktemp -d "$PROG.XXXXXXXXX")"
}

tearDownTests() {
	rm -rf -- "$WORKDIR"
}

for s in \
	quote_sed_regexp quote_shell string_quote_remove \
	opt_check_dir opt_check_number opt_check_read \
	getopt signal \
	fatal message verbose \
	;
do
	. "./$s"
	registerTests "./$s"
done

runUnitTests
