#!/bin/sh

appendTests string_quote_remove_test1
string_quote_remove_test1() {
	. ../shell-quote

	local string='"test passed"'
	local result="$(string_quote_remove "$string")"
	assertEquals "$string" "$result" 'test passed'
}

appendTests string_quote_remove_test2
string_quote_remove_test2() {
	. ../shell-quote

	local string="'test passed'"
	local result="$(string_quote_remove "$string")"
	assertEquals "$string" "$result" 'test passed'
}

appendTests string_quote_remove_test3
string_quote_remove_test3() {
	. ../shell-quote

	local string="'test passed\""
	local result="$(string_quote_remove "$string")"
	assertEquals "$string" "$result" "'test passed\""
}

appendTests string_quote_remove_test4
string_quote_remove_test4() {
	. ../shell-quote

	local string="test ' passed"
	local result="$(string_quote_remove "$string")"
	assertEquals "$string" "$result" "test ' passed"
}
