#!/bin/sh

appendTests string_quote_remove_test1
string_quote_remove_test1() {
	. ../shell-quote

	local string='"test passed"'
	local result="$(string_quote_remove "$string")"
	if [ "$result" != 'test passed' ]; then
		printf '%s' "$string"
		return 1
	fi
}

appendTests string_quote_remove_test2
string_quote_remove_test2() {
	. ../shell-quote

	local string="'test passed'"
	local result="$(string_quote_remove "$string")"
	if [ "$result" != 'test passed' ]; then
		printf '%s' "$string"
		return 1
	fi
}

appendTests string_quote_remove_test3
string_quote_remove_test3() {
	. ../shell-quote

	local string="'test passed\""
	local result="$(string_quote_remove "$string")"
	if [ "$result" != "'test passed\"" ]; then
		printf '%s' "$string"
		return 1
	fi
}

appendTests string_quote_remove_test4
string_quote_remove_test4() {
	. ../shell-quote

	local string="test ' passed"
	local result="$(string_quote_remove "$string")"
	if [ "$result" != "test ' passed" ]; then
		printf '%s' "$string"
		return 1
	fi
}
