#!/bin/sh

appendTests shell_args_test1
shell_args_test1() {
	. ../shell-args

	if [ ! -f "$WORKDIR/file-000" ]; then
		> "$WORKDIR/file-000"
		chmod 000 "$WORKDIR/file-000"
	fi
	cd "$WORKDIR"

	expect="$(message "FILE: ./file-000: file not available." 2>&1)"
	result="$(opt_check_read "FILE" "./file-000" 2>&1)" ||:
	
	if [ "$result" != "$expect" ]; then
		printf 'opt_check_read(): %s' "$result"
		return 1
	fi
}
appendTests shell_args_test2
shell_args_test2() {
	. ../shell-args

	if [ ! -f "$WORKDIR/file-200" ]; then
		> "$WORKDIR/file-200"
		chmod 200 "$WORKDIR/file-200"
	fi
	cd "$WORKDIR"

	expect="$(message "FILE: ./file-200: file not available." 2>&1)"
	result="$(opt_check_read "FILE" "./file-200" 2>&1)" ||:
	
	if [ "$result" != "$expect" ]; then
		printf 'opt_check_read(): %s' "$result"
		return 1
	fi
}

appendTests shell_args_test3
shell_args_test3() {
	. ../shell-args

	if [ ! -f "$WORKDIR/file-644" ]; then
		> "$WORKDIR/file-644"
		chmod 644 "$WORKDIR/file-644"
	fi
	cd "$WORKDIR"

	expect="$(readlink -ev ./file-644)"
	result="$(opt_check_read "FILE" "./file-644" 2>&1)" ||:
	
	if [ "$result" != "$expect" ]; then
		printf 'opt_check_read(): %s' "$result"
		return 1
	fi
}

appendTests shell_args_test4
shell_args_test4() {
	. ../shell-args

	if [ ! -e "$WORKDIR/broken-symlink" ]; then
		ln -s "$WORKDIR/broken-symlink" "$WORKDIR/broken-symlink"
	fi
	cd "$WORKDIR"

	expect="$(message "FILE: ./broken-symlink: file not available." 2>&1)"
	result="$(opt_check_read "FILE" "./broken-symlink" 2>&1)" ||:
	
	if [ "$result" != "$expect" ]; then
		printf 'opt_check_read(): %s' "$result"
		return 1
	fi
}


appendTests shell_args_test5
shell_args_test5() {
	. ../shell-args

	[ -d "$WORKDIR/dir-644" ] ||
		mkdir -m644 "$WORKDIR/dir-644"
	cd "$WORKDIR"

	expect="$(message "DIR: ./dir-644: directory not available." 2>&1)"
	result="$(opt_check_dir "DIR" "./dir-644" 2>&1)" ||:
	rmdir "dir-644"

	if [ "$result" != "$expect" ]; then
		printf 'opt_check_dir(): %s' "$result"
		return 1
	fi
}

appendTests shell_args_test6
shell_args_test6() {
	. ../shell-args

	[ -d "$WORKDIR/dir-755" ] ||
		mkdir -m755 "$WORKDIR/dir-755"
	cd "$WORKDIR"

	expect="$(readlink -ev ./dir-755 2>&1)" ||:
	result="$(opt_check_dir "DIR" "./dir-755" 2>&1)" ||:
	rmdir "dir-755"

	if [ "$result" != "$expect" ]; then
		printf 'opt_check_dir(): %s' "$result"
		return 1
	fi
}

appendTests shell_args_test7
shell_args_test7() {
	. ../shell-args

	string="1234"
	expect="1234"
	result="$(opt_check_number "NUM" "$string" 2>&1)" ||:

	if [ "$result" != "$expect" ]; then
		printf 'opt_check_number(): %s' "$result"
		return 1
	fi
}

appendTests shell_args_test8
shell_args_test8() {
	. ../shell-args

	string="0001"
	expect="$(message "NUM: $string: invalid number." 2>&1)"
	result="$(opt_check_number "NUM" "$string" 2>&1)" ||:

	if [ "$result" != "$expect" ]; then
		printf 'opt_check_number(): %s' "$result"
		return 1
	fi
}

appendTests shell_args_test9
shell_args_test9() {
	. ../shell-args

	string="1 2"
	expect="$(message "NUM: $string: invalid number." 2>&1)"
	result="$(opt_check_number "NUM" "$string" 2>&1)" ||:

	if [ "$result" != "$expect" ]; then
		printf 'opt_check_number(): %s' "$result"
		return 1
	fi
}
