#!/bin/sh

appendTests shell_quote_test1
shell_quote_test1() {
	. ../shell-quote
	local string='.*'
	local regexp="$(quote_sed_regexp "$string")"
	local result="$(printf '%s\n' "$string passed" |sed -e "s/^$regexp/test/")"
	if [ "$result" != 'test passed' ]; then
		printf 'quote_sed_regexp(): %s' "$string"
		return 1
	fi
}

appendTests shell_quote_test2
shell_quote_test2() {
	. ../shell-quote
	local string='[[:space:]]'
	local regexp="$(quote_sed_regexp "$string")"
	local result="$(printf '%s\n' "test $string" |sed -e "s/$regexp/passed/")"
	if [ "$result" != 'test passed' ]; then
		printf 'quote_sed_regexp(): %s' "$string"
		return 1
	fi
}

appendTests shell_quote_test3
shell_quote_test3() {
	. ../shell-quote
	local string='t{1,3}'
	local regexp="$(quote_sed_regexp "$string")"
	local result="$(printf '%s\n' "test$string passed" |sed -e "s/$regexp//")"
	if [ "$result" != 'test passed' ]; then
		printf 'quote_sed_regexp(): %s' "$string"
		return 1
	fi
}

appendTests shell_quote_test4
shell_quote_test4() {
	. ../shell-quote
	local string='&\1'
	local regexp="$(quote_sed_regexp "$string")"
	local result="$(printf '%s\n' "test not passed" |sed -e "s/\(not\)/$regexp/")" #"
	if [ "$result" != 'test &\1 passed' ]; then
		printf 'quote_sed_regexp(): %s' "$string"
		return 1
	fi
}

appendTests shell_quote_test5
shell_quote_test5() {
	. ../shell-quote
	local string='`true`'
	local result
	eval "result=\"$(quote_shell "$string")\""
	if [ "$result" != "$string" ]; then
		printf 'quote_shell(): %s' "$string"
		return 1
	fi
}

appendTests shell_quote_test6
shell_quote_test6() {
	. ../shell-quote
	local string='$(true)'
	local result
	eval "result=\"$(quote_shell "$string")\""
	if [ "$result" != "$string" ]; then
		printf 'quote_shell(): %s' "$string"
		return 1
	fi
}

appendTests shell_quote_test7
shell_quote_test7() {
	. ../shell-quote
	local string='\`true\`; echo zzz'
	local result
	eval "result=\"$(quote_shell "$string")\""
	if [ "$result" != "$string" ]; then
		printf 'quote_shell(): %s' "$string"
		return 1
	fi
}

appendTests shell_quote_test8
shell_quote_test8() {
	__libshell_experimental=1
	. ../shell-quote

	local string='"test passed"'
	local result="$(string_quote_remove "$string")"
	if [ "$result" != 'test passed' ]; then
		printf 'string_quote_remove(): %s' "$string"
		return 1
	fi
}

appendTests shell_quote_test9
shell_quote_test9() {
	__libshell_experimental=1
	. ../shell-quote

	local string="'test passed'"
	local result="$(string_quote_remove "$string")"
	if [ "$result" != 'test passed' ]; then
		printf 'string_quote_remove(): %s' "$string"
		return 1
	fi
}

appendTests shell_quote_test10
shell_quote_test10() {
	__libshell_experimental=1
	. ../shell-quote

	local string="'test passed\""
	local result="$(string_quote_remove "$string")"
	if [ "$result" != "'test passed\"" ]; then
		printf 'string_quote_remove(): %s' "$string"
		return 1
	fi
}

appendTests shell_quote_test11
shell_quote_test11() {
	__libshell_experimental=1
	. ../shell-quote

	local string="test ' passed"
	local result="$(string_quote_remove "$string")"
	if [ "$result" != "test ' passed" ]; then
		printf 'string_quote_remove(): %s' "$string"
		return 1
	fi
}
