#!/bin/ash -efu

PROG='TEST'

appendTests verbose_test1
verbose_test1() {
	. ../shell-error
	verbose=1
	expect="$PROG: message message;"
	result=`verbose "message message" 2>&1 |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}

appendTests verbose_test2
verbose_test2() {
	. ../shell-error
	verbose=
	expect=
	result=`verbose "message message" 2>&1 |tr '\n' ';'`
	assertEquals "$result" "$result" "$expect"
}
