#!/bin/sh -efu

if [ -z "${__included_shell_config-}" ]; then
__included_shell_config=1

. shell-error
. shell-quote

__shell_config_comment='#'

shell_config_get() {
	[ "$#" -ge 2 -a "$#" -le 3 ] ||
		fatal "Usage: shell_config_get file name [delim]"

	[ -s "$1" ] ||
		return 0
	local n
	n="$(quote_sed_regexp "$2")"
	sed -n -e "s/^[[:space:]]*$n${3:-=}//p" -- "$1"
}

shell_config_set() {
	[ "$#" -ge 3 -a "$#" -le 5 ] ||
		fatal "Usage: shell_config_get file name value [read-delim [write-delim]]"

	local n v created=

	if [ ! -f "$1" ]; then
		if [ ! -w "${1%/*}" ]; then
			message "${1%/*}: not writable."
			return 1
		fi
		touch -- "$1" ||
			return 1
		created=1
	fi

	if [ -z "$created" ]; then
		n="$(quote_sed_regexp "$2")"

		if v="$(grep --mmap -m1 "^[[:space:]]*$n${4-=}" -- "$1" 2>/dev/null)"; then
			[ "${v#*$2${4-=}}" = "$3" ] ||
				sed -i -e "s/^[[:space:]]*$n${4-=}.*/$2${5-=}$3/" -- "$1"
			return
		fi

		if [ -n "${__shell_config_comment-}" ] &&
		   v="$(grep --mmap -m1 "^[[:space:]]*${__shell_config_comment:-#}[[:space:]]*$n${4-=}" -- "$1" 2>/dev/null)"; then
			v="$(quote_sed_regexp "$v")"
			sed -i -e "s/^$v\$/$2${5-=}$3/" -- "$1"
			return
		fi
	fi

	printf '%s\n' "$2${5-=}$3" >> "$1"
}

fi #__included_shell_config
