#!/bin/sh -efu
### This file is covered by the GNU General Public License,
### which should be included with libshell as the file LICENSE.
### All copyright information are listed in the COPYING.

if [ -z "${__included_shell_string-}" ]; then
__included_shell_string=1

### Creates a mask of equal length string.
### Usage: fill_mask var str [full-length]
fill_mask()
{
	local __m= __v="$1" __s="$2"
	[ -n "${3-}" ] || __s="${__s#?}"
	while :; do
		case $((${#__s} - ${#__m})) in
			0) break ;;
			1) __m="$__m?" ;;
			2) __m="$__m??" ;;
			3) __m="$__m???" ;;
			4) __m="$__m????" ;;
			5) __m="$__m?????" ;;
			6) __m="$__m??????" ;;
			7) __m="$__m???????" ;;
			8) __m="$__m????????" ;;
			9) __m="$__m?????????" ;;
			*) __m="$__m??????????" ;;
		esac
	done
	eval "$__v=\$__m"
}

fi #__included_shell_string
