#!/bin/sh -efu

if [ -z "${__included_shell_mail_adress-}" ]; then
__included_shell_mail_adress=1

readonly regex_byte='([0-9]{1,2}|1[0-9][0-9]|2[0-5][0-5])'
readonly regex_ipv4="$regex_byte\.$regex_byte\.$regex_byte\.$regex_byte"

if [ -n "${shell_mail_adress_strict-}" ]; then
	# http://en.wikipedia.org/wiki/Country_code_top-level_domain
	readonly regex_cctld_active='(a[cdefgilmnoqrstuwxz]|b[abdefghijmnorstwyz]|c[acdfghiklmnoruvxyz]|d[ejkmoz]|e[cegrstu]|f[ijkmor]|g[adefghilmnpqrstuwy]|h[kmnrtu]|i[delmnoqrst]|j[emop]|k[eghimnprwyz]|l[abcikrstuvy]|m[acdeghklmnopqrstuvwxyz]|n[acefgilopruz]|om|p[aefghklnrstwy]|qa|r[eosuw]|s[abcdeghiklmnrtuvyz]|t[cdfghjklmnortvwz]|u[agksyz]|v[aceginu]|w[fs]|ye|z[amw])'
	readonly regex_cctld_reserved='(um|bl|eh|mf)'
	readonly regex_cctld_allocated='(bv|gb|pm|sj|so|yt)'
	readonly regex_cctld_phaseout='(tp|yu)'
	readonly regex_cctld_deleted='(cs|dd|zr)'
	readonly regex_gtld='(aero|arpa|asia|biz|cat|com|coop|edu|gov|info|int|jobs|mil|mobi|museum|name|net|org|pro|tel|travel)'

	regex_tld="($regex_gtld|$regex_cctld_active|$regex_cctld_reserved|$regex_cctld_allocated|$regex_cctld_phaseout)"
else
	regex_tld='([a-zA-Z]{2,4}|museum)'
fi

# 6. ADDRESS SPECIFICATION (http://tools.ietf.org/html/rfc822)
#
# addr-spec   =  local-part "@" domain        ; global address
# local-part  =  word *("." word)             ; uninterpreted
#                                             ; case-preserved
# domain      =  sub-domain *("." sub-domain)
# sub-domain  =  domain-ref / domain-literal
# domain-ref  =  atom                         ; symbolic reference
#
# 6.2.3. DOMAIN TERMS
# A domain-ref must be THE official name of a registry, network,
# or host.
#
readonly regex_domain="([a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*)\.$regex_tld"
readonly regex_email="([_a-z0-9-]+(\.[_a-z0-9-]+)*)@($regex_ipv4|$regex_domain)"

valid_email() {
	local email="$1"
	printf '%s' "$email" |
		egrep -iqs "^$regex_email\$" ||
		return 1
}

valid_ipv4() {
	local ipaddr="$1"
	printf '%s' "$ipaddr" |
		egrep -iqs "^$regex_ipv4\$" ||
		return 1
}

fi #__included_shell_mail_adress
