name: Lint

on:
  push:
    branches: [ master, for-master ]
  pull_request:
    branches: [ master, for-master ]

jobs:
  lint-shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "install tools"
        run: sudo apt-get -y -qq install shellcheck
      - name: "shellcheck"
        run: make verify

  check-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "install tools"
        run: sudo apt-get -y -qq install scdoc
      - name: "make docs"
        run: make man

  check-dash:
    runs-on: ubuntu-latest
    needs: [ lint-shell ]
    steps:
      - uses: actions/checkout@v2
      - name: "install tools"
        run: sudo apt-get -y -qq install dash
      - name: "unittests"
        run: make check CHECK_SHELL=/bin/dash V=1

  check-bash:
    runs-on: ubuntu-latest
    needs: [ lint-shell ]
    steps:
      - uses: actions/checkout@v2
      - name: "install tools"
        run: sudo apt-get -y -qq install bash
      - name: "unittests"
        run: make check CHECK_SHELL=/bin/bash V=1

  check-mksh:
    runs-on: ubuntu-latest
    needs: [ lint-shell ]
    steps:
      - uses: actions/checkout@v2
      - name: "install tools"
        run: sudo apt-get -y -qq install mksh
      - name: "unittests"
        run: make check CHECK_SHELL=/bin/mksh V=1
