name: Lint

on:
  push:
    branches: [ master, for-master ]
  pull_request:
    branches: [ master, for-master ]

jobs:
  check-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Current environ"
        run: env | sort

      - name: "github object"
        run: |
          cat >/dev/null <<EOF
          ${{ toJSON(github) }}
          EOF

      - name: "github event"
        run: |
          cat >/dev/null <<EOF
          ${{ toJSON(github.event) }}
          EOF

      - name: "Developer's Certificate of Origin"
        run: |
          [ "${{ github.event_name }}" = "push" ] &&
             from="refs/remotes/origin/${{ github.event.repository.default_branch }}" ||
             from="${{ github.event.pull_request.base.sha }}"
          .github/dco.sh "$from..HEAD"

  lint-shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get -y -qq install shellcheck
      - run: make verify

  check-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get -y -qq install scdoc
      - run: make man

  check-shells:
    runs-on: ubuntu-latest
    needs:
      - lint-shell
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: dash
            pkgs: dash

          - name: bash
            pkgs: bash

          - name: mksh
            pkgs: mksh

          - name: lksh
            pkgs: mksh

    name: "check with ${{ matrix.name }}"
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get -y -qq install ${{ matrix.pkgs }}
      - run: make check V=1 CHECK_SHELL=/bin/${{ matrix.name }}
